"""add img_url

Revision ID: 12c99539962d
Revises: 6df0f6b25080
Create Date: 2024-03-04 15:27:40.109279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c99539962d'
down_revision: Union[str, None] = '6df0f6b25080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'img_url')
    # ### end Alembic commands ###
